trigger:
- main

pool:
    vmImage: ubuntu-latest

variables:
    bulidConfiguration: 'Release'

steps:
-script: dotnet buld --configuration $(buildConfiguration)
displayName: 'dotnet build $(buildConfiguration)'